import Footer from "@/shared/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {children}
        <Footer /> {/* ✅ Now it's a child of <body>, which is valid */}
      </body>
    </html>
  );
}
